### PR TITLE
finding factorial using function

### PR DESCRIPTION
**Pull request by iamneeraj542**
Here, using the function of a number entered by the user.

Basically, the Factorial of n is the product of all positive descending integers. The factorial of n is denoted by n!

### CODE REVIEW

**Comment by neeraj542** [comment]
ok thanks for using function. Do you know that it can be possible by using recursion.

**Comment by neeraj542** [comment]
Recursion is also make this repo best if we will add its seperate program. So, you can pass other programs folder in this.

**Comment by neeraj542** [comment]
okay, thank you for implementation and also for your contributon.

**Comment by iamneeraj542** [comment]
Yes, We can use recursion here :-)

**Pull request merged**
